# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-devops-usa

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    NEXT_PUBLIC_DR_API_BASE_URL: '$(NEXT_PUBLIC_DR_API_BASE_URL)'
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    set -e
    npm install --force
    npm run build
    mkdir dr-phase-2-ui
    tar -czvf dr-1-$(Build.BuildId).tar.gz .next public src next-env.d.ts tsconfig.json package.json next.config.js .eslintrc.json
  displayName: 'npm install and build'
# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(system.defaultworkingdirectory)' 
#     targetFolder: '$(Build.ArtifactStagingDirectory)/.next'
#   displayName: 'Copy npm package'

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderFile: '$(system.defaultworkingdirectory)/.next'
#     includeRootFolder: true
#     archiveType: tar
#     replaceExistingArchive: true
#     archiveFile: '$(system.defaultworkingdirectory)/.next/.next.tar.gz'
# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '.next'
#     includeRootFolder: true
#     archiveType: 'tar'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/rbs-Ip-$(Build.BuildId).tar.gz'
#     replaceExistingArchive: true
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*tar.gz
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: '
  inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)/dr-1-$(Build.BuildId).tar.gz'
       condition: succeededOrFailed()