import MainCoursesDynimicData from "@/data/newComponentData/dynamicComponentData/MainCoursesDynimicData";

const pageMappings = [
  {
    pages: [
      "data-science",
      // =========multiple pages===========
      "data-science-course",
      "data-science-courses",
      "courses-in-data-science",
      "course-for-data-science",
      "data-science-online-courses",
      "data-science-course-online",
      "courses-data-science",
      "online-data-science-courses",
      "best-data-science-courses",
      "a-crash-course-in-data-science",
      "data-science-courses-online",
      "python-data-science-course",
      "best-online-data-science-courses",
      "data-science-certification-course",
      "online-course-in-data-science",
      "online-data-science-course",
    ],
    data: MainCoursesDynimicData.DataScience,
  },
  {
    pages: [
      "online-courses",
      "online-course",
      "courses-online",
      "online-coding-courses",
      "online-courses-with-certificates",
      "online-certification-courses",
      "coding-courses-online",
      "IT-courses-online",
      "online-certificate-courses",
      "online-courses-for-adults",
      "best-online-courses",
      "online-it-courses",
      "online-certificate-course",
      "online-courses-certificates",
      "online-training-courses",
      "certificate-courses-online",
    ],
    data: undefined,
  },
  {
    pages: [
      "digital-marketing",
      // =========multiple pages===========
      "what-is-digital-marketing",
      "digital-marketing-jobs",
      "digital-marketing-salary",
      "digital-marketer",
      "digital-marketing-course",
      "digital-marketing-strategy",
      "digital-marketing-certificate",
      "google-digital-marketing-certification",
      "digital-marketing-courses",
      "digital-marketing-near-me",
      "digital-marketing-specialist",
      "digital-marketing-certification",
      "digital-marketing-degree",
      "digital-marketing-tools",
      "digital-marketing-training",
      "digital-marketing-certificates",
      "digital-marketing-institute",
      "digital-marketing-strategies",
      "digital-marketing-course-online",
      "digital-marketing-definition",
      "digital-marketing-examples",
      "digital-marketing-meaning",
      "digital-marketing-trends",
      "learn-digital-marketing",
      "types-of-digital-marketing",
      "digital-marketer-salary",
      "digital-marketing-classes",
      "digital-marketing-online-courses",
      "online-digital-marketing-courses",
      "what-is-a-digital-marketer",
      "digital-marketing-courses-online",
      "google-digital-marketing-course",
      "how-to-become-a-digital-marketer",
      "how-to-do-digital-marketing",
      "how-to-start-digital-marketing",
      "online-digital-marketing",
      "digital-marketing-blogs",
      "digital-marketing-careers",
      "digital-marketing-certificate-online",
      "digital-marketing-certifications",
      "fundamentals-of-digital-marketing",
      "online-digital-marketing-course",
      "what-does-a-digital-marketer-do",
      "what's-digital-marketing",
      "best-digital-marketing-services",
      "certificate-in-digital-marketing",
      "digital-marketing-platforms",
      "digital-marketing-tips",
      "masters-in-digital-marketing",
      "what-is-a-digital-marketing",
      "best-digital-marketing-courses",
      "definition-of-digital-marketing",
      "digital-marketing-degree-online",
      "digital-marketing-degrees",
      "digital-marketing-experts",
      "digital-marketing-online",
      "examples-of-digital-marketing",
      "how-to-learn-digital-marketing",
      "future-of-digital-marketing",
      "importance-of-digital-marketing",
      "why-is-digital-marketing-important",
    ],
    data: MainCoursesDynimicData.DigitalMarketing,
  },
  {
    pages: [
      "project-management",
      // =========multiple pages===========
      "project-management-courses",
      "project-management-course",
      "project-management-courses-online",
      "project-manager-course",
      "online-project-management-courses",
      "project-managment-courses",
      "what-skills-can-you-get-from-managing-it-projects-course",
      "courses-in-project-management",
      "online-course-for-project-management",
      "online-course-in-project-management",
      "project-management-online-course",
      "project-manager-courses",
      "project-managing-courses",
      "project-management-certification-courses",
      "project-management-course-online",
      "project-management-online-courses",
      "project-management-training-courses",
      "agile-project-management-course",
      "construction-project-management-courses",
      "best-project-management-courses",
      "online-courses-project-management",
      "online-project-management-course",
      "project-manager-courses-online",
      "project-managment-course",
      "course-in-project-management",
      "project-management-courses-for-beginners",
      "project-management-on-line-courses",
    ],

    data: MainCoursesDynimicData.ProjectManagement,
  },
  {
    pages: [
      "cyber-security",
      // =========multiple pages===========
      "cyber-security-course",
      "cyber-security-courses",
      "cyber-security-courses-online",
      "cyber-security-course-online",
      "online-cyber-security-course",
      "online-cyber-security-courses",
      "cyber-security-online-courses",
      "courses-for-cyber-security",
      "courses-cyber-security",
      "cyber-security-training-courses",
      "cyber-security-courses-for-beginners",
      "online-course-for-cyber-security",
      "courses-in-cyber-security",
      "cyber-security-courses-near-me",
      "cyber-security-online-course",
      "best-cyber-security-courses",
      "cyber-security-courses-offered",
      "government-funded-cyber-security-courses",
      "online-courses-for-cyber-security",
    ],
    data: MainCoursesDynimicData.CyberSecurity,
  },
  {
    pages: [
      "artificial-intelligence",
      // =========multiple pages===========
      "artificial-intelligence-course",
      "artificial-general-intelligence-course",
      "artificial-intelligence-courses",
      "artificial-intelligence-online-course",
      "course-on-artificial-intelligence",
      "courses-on-artificial-intelligence",
      "course-artificial-intelligence",
      "artificial-intelligence-course-online",
      "best-artificial-intelligence-course",
      "machine-learning-and-artificial-intelligence-courses",
      "online-artificial-intelligence-courses",
      "artificial-intelligence-course-free",
      "artificial-intelligence-course-syllabus",
      "artificial-intelligence-training-courses",
      "online-artificial-intelligence-course",
      "online-course-artificial-intelligence",
    ],
    data: MainCoursesDynimicData.ArtificialIntelligence,
  },
  {
    pages: [
      "design-thinking",
      // =========multiple pages===========
      "design-thinking-process",
      "what-is-design-thinking",
      "design-thinking-definition",
      "design-thinking-certification",
      "design-thinking-course",
      "design-thinking-process-steps",
      "design-thinking-training",
      "design-thinking-model",
      "design-thinking-tools",
      "design-thinking-courses",
      "design-thinking-definition",
      "design-thinking-stages",
      "definition-of-design-thinking",
      "design-thinking-approach",
      "5-stages-of-design-thinking",
      "design-thinking-jobs",
      "design-thinking-methods",
      "design-thinking-step",
      "what-is-design-thinking-process",
      "design-thinking-certificate",
      "design-thinking-for-educators",
      "what-is-one-of-the-tools-associated-with-design-thinking",
      "benefits-of-design-thinking",
      "design-thinking-bootcamp",
      "design-thinking-in-education",
      "design-thinking-meaning",
      "design-thinking-methodologies",
      "systems-thinking-vs-design-thinking",
    ],
    data: MainCoursesDynimicData.DesignThinking,
  },
  {
    pages: [
      "full-stack-development",
      // =========multiple pages===========
      "full-stack-developer",
      "full-stack-developer-salary",
      "what-is-a-full-stack-developer",
      "full-stack-development",
      "full-stack-developer-jobs",
      "what-is-full-stack-development",
      "full-stack-web-developer",
      "full-stack-web-development",
      "full-stack-development-course",
      "what-is-full-stack-web-development",
      "what-is-full-stack-development",
      "full-stack-web-development",
      "full-stack-development-certificate",
      "full-stack-web-development-certificate",
      "full-stack-web-development-certification",
      "what-is-full-stack-software-development",
      "full-stack-development-courses",
      "full-stack-development-meaning",
      "full-stack-software-development",
      "learn-full-stack-web-development",
    ],
    data: MainCoursesDynimicData.FullStackDeveloper,
  },
  {
    pages: [
      "data-and-business-analytics",
      // =========multiple pages===========
      "data-analysis",
      "business-analytics",
      "what-is-business-analytics",
      "what-is-data-analysis",
      "data-analysis-definition",
      "data-analysis-example",
      "data-analysis-methods",
      "data-analysis-techniques",
      "types-of-data-analysis",
      "data-analysis-meaning",
      "data-analysis-steps",
      "no-code-tools",
      "business-analytics-meaning",
      "data-science-and-business-analytics",
      "define-business-analytics",
      "data-science-and-business-analytics-degree",
      "data-science-and-business-analytics-course",
      "data-science-and-business-analytics-salary",
      "difference-between-data-science-and-business-analytics",
      "data-science-and-business-analytics-online-course",
      "what-is-data-science-and-business-analytics",
    ],
    data: MainCoursesDynimicData.DataAndBusinessAnalytics,
  },
  {
    pages: [
      "management-advancement",
      // =========multiple pages===========
      "mdp",
      "management-development-courses",
      "management-certificate-programs",
      "management-development-program",
      "mdp-meaning",
      "management-development-programs-include",
      "leadership-and-management-development",
      "professional-development-courses-for-managers",
      "best-management-development-programs",
      "management-development-program-jobs",
      "management-development-program-salary",
    ],
    data: MainCoursesDynimicData.ManagementAdvancement,
  },
  {
    pages: ["product-management"],
    data: MainCoursesDynimicData.ProductManagement,
  },
];

const DataSeparatorPages = (page: string | undefined): any | undefined => {
  if (!page) return undefined;

  for (const mapping of pageMappings) {
    if (mapping.pages.includes(page)) {
      return {
        ...mapping.data,
      };
    }
  }

  return undefined;
};

export default DataSeparatorPages;
