import MultiplePagesCoursesData from "@/data/newComponentData/multiplePagesData/MultiplePagesCoursesData";
import MainCoursesDynimicData from "@/data/newComponentData/dynamicComponentData/MainCoursesDynimicData";

const pageMappings = [
  {
    pages: [
      "data-science-course",
      "data-science-courses",
      "courses-in-data-science",
      "course-for-data-science",
      "data-science-online-courses",
      "data-science-course-online",
      "courses-data-science",
      "online-data-science-courses",
      "best-data-science-courses",
      "a-crash-course-in-data-science",
      "data-science-courses-online",
      "python-data-science-course",
      "best-online-data-science-courses",
      "data-science-certification-course",
      "online-course-in-data-science",
      "online-data-science-course",
    ],
    data: MainCoursesDynimicData.DataScience,
  },
  {
    pages: [
      "online-courses",
      "online-course",
      "courses-online",
      "online-coding-courses",
      "online-courses-with-certificates",
      "online-certification-courses",
      "coding-courses-online",
      "IT-courses-online",
      "online-certificate-courses",
      "online-courses-for-adults",
      "best-online-courses",
      "online-it-courses",
      "online-certificate-course",
      "online-courses-certificates",
      "online-training-courses",
      "certificate-courses-online",
    ],
    data: undefined,
  },
  {
    pages: [
      "digital-marketing",
      "what-is-digital-marketing",
      "digital-marketing-jobs",
      "digital-marketing-salary",
      "digital-marketer",
      "digital-marketing-course",
      "digital-marketing-strategy",
      "digital-marketing-certificate",
      "google-digital-marketing-certification",
      "digital-marketing-courses",
      "digital-marketing-near-me",
      "digital-marketing-specialist",
      "digital-marketing-certification",
      "digital-marketing-degree",
      "digital-marketing-tools",
      "digital-marketing-training",
      "digital-marketing-certificates",
      "digital-marketing-institute",
      "digital-marketing-strategies",
      "digital-marketing-course-online",
      "digital-marketing-definition",
      "digital-marketing-examples",
      "digital-marketing-meaning",
      "digital-marketing-trends",
      "learn-digital-marketing",
      "types-of-digital-marketing",
      "digital-marketer-salary",
      "digital-marketing-classes",
      "digital-marketing-online-courses",
      "online-digital-marketing-courses",
      "what-is-a-digital-marketer",
      "digital-marketing-courses-online",
      "google-digital-marketing-course",
      "how-to-become-a-digital-marketer",
      "how-to-do-digital-marketing",
      "how-to-start-digital-marketing",
      "online-digital-marketing",
      "digital-marketing-blogs",
      "digital-marketing-careers",
      "digital-marketing-certificate-online",
      "digital-marketing-certifications",
      "fundamentals-of-digital-marketing",
      "online-digital-marketing-course",
      "what-does-a-digital-marketer-do",
      "what's-digital-marketing",
      "best-digital-marketing-services",
      "certificate-in-digital-marketing",
      "digital-marketing-platforms",
      "digital-marketing-tips",
      "masters-in-digital-marketing",
      "what-is-a-digital-marketing",
      "best-digital-marketing-courses",
      "definition-of-digital-marketing",
      "digital-marketing-degree-online",
      "digital-marketing-degrees",
      "digital-marketing-experts",
      "digital-marketing-online",
      "examples-of-digital-marketing",
      "how-to-learn-digital-marketing",
      "future-of-digital-marketing",
      "importance-of-digital-marketing",
      "why-is-digital-marketing-important",
    ],
    data: MainCoursesDynimicData.DigitalMarketing,
  },
  {
    pages: [
      "project-management-courses",
      "project-management-course",
      "project-management-courses-online",
      "project-manager-course",
      "online-project-management-courses",
      "project-managment-courses",
      "what-skills-can-you-get-from-managing-it-projects-course",
      "courses-in-project-management",
      "online-course-for-project-management",
      "online-course-in-project-management",
      "project-management-online-course",
      "project-manager-courses",
      "project-managing-courses",
      "project-management-certification-courses",
      "project-management-course-online",
      "project-management-online-courses",
      "project-management-training-courses",
      "agile-project-management-course",
      "construction-project-management-courses",
      "best-project-management-courses",
      "online-courses-project-management",
      "online-project-management-course",
      "project-manager-courses-online",
      "project-managment-course",
      "course-in-project-management",
      "project-management-courses-for-beginners",
      "project-management-on-line-courses",
    ],

    data: MainCoursesDynimicData.ProjectManagement,
  },
  {
    pages: ["cyber-security-course"],
    data: MainCoursesDynimicData.CyberSecurity,
  },
  {
    pages: ["artificial-intelligence-course"],
    data: MainCoursesDynimicData.ArtificialIntelligence,
  },
  {
    pages: ["design-thinking"],
    data: MainCoursesDynimicData.DesignThinking,
  },
  {
    pages: ["full-stack-developer"],
    data: MainCoursesDynimicData.FullStackDeveloper,
  },
  {
    pages: ["data-analysis"],
    data: MainCoursesDynimicData.DataAndBusinessAnalytics,
  },
  {
    pages: ["mdp"],
    data: MainCoursesDynimicData.ManagementAdvancement,
  },
];

const DataSeparatorPages = (page: string | undefined): any | undefined => {
  if (!page) return undefined;

  for (const mapping of pageMappings) {
    if (mapping.pages.includes(page)) {
      return {
        ...mapping.data,
        multiplePagesDatas: MultiplePagesCoursesData[page],
      };
    }
  }

  return undefined;
};

export default DataSeparatorPages;
